name: MusiBoard
version: ${version}
main: io.musician101.musiboard.MusiBoard
api-version: 1.20
author: Musician101
commands:
  musiboard:
    aliases: [ mb ]
  objectives: { }
  players: { }
  scoreboard: { }
  team: { }
